### ISSUE TITLE
finalize the jumpscript extension in the agent and JS utils

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/agent2#38]

**Comment by despiegk** [comment]
make sure its easy to execute jumpscripts & its explained well

**Comment by muhamadazmy** [comment]
Done

Client docs:
https://gig.gitbooks.io/jumpscale/content/MultiNode/AgentController2/Python%20Client.html#acclient.Client.execute_jumpscript

Example:
https://gig.gitbooks.io/jumpscale/content/MultiNode/AgentController2/Jumpscripts.html
