### ISSUE TITLE
Bundle syncthing with agent2

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/agent2#40]
Binary repo should work independant of AYS.

**Comment by muhamadazmy** [comment]
Done
binary/agent2 repo on gitaydo now has the agent with the embedded `syncthing` extension.

> Note that, you will probably need to tweak the agent config before starting it standalone (without jumpscale) because the config comes with some helper extensions and startup commands that are designed to speed up jumpscripts exectuions.

So to star the agent standalone (with no jumpscripts support). open the toml file and remove the `startup.legacy` and `startup.jumpscript` sections.
