### ISSUE TITLE
Rework jumpscripts sharing when working with 2 agent controllers

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/agent2#47]
Syncthing will misbehave when you try to sync 1 slave folder with 2 masters. So we will rework this to sync under different folders for each agent controller.

**Comment by despiegk** [comment]
main logic should be sending jumpscripts with using the hashing method
as discussed before

so why do we need this?

because the hashing method is much more safe?



On Sun, Oct 18, 2015 at 9:26 AM, Muhamad Azmy <notifications@github.com>
wrote:

> Syncthing will misbehave when you try to sync 1 slave folder with 2
> masters. So we will rework this to sync under different folders for each
> agent controller.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/agent2/issues/47>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by muhamadazmy** [comment]
The hashing method is already implemented and working. But we never dropped the support of sharing scripts over syncthing. And out of completeness this should work flawlessly when having a multiple agent controller environment.

**Comment by despiegk** [comment]
indeed

On Sun, Oct 18, 2015 at 10:30 AM, Muhamad Azmy <notifications@github.com>
wrote:

> The hashing method is already implemented and working. But we never
> dropped the support of sharing scripts over syncthing. And out of
> completeness this should work flawlessly when having a multiple agent
> controller environment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/agent2/issues/47#issuecomment-148991175>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by muhamadazmy** [comment]
Done
