### ISSUE TITLE
jumpscale 7.1 compatibility with this jsagent

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/agent2#8]
prob best to change current jumpscale agentcontroller client and keep interface same
goal is
- we don't use the current agentcontroller server code any longer
- no more python in agent / ac

**Comment by muhamadazmy** [comment]
@grimpy Can you please specify what's missing on this since you already had some progress on it before you leave for vacation?

**Comment by muhamadazmy** [comment]
TODO:
 - Package syncthing
 - Package legacy scripts
 - Update startup events to start sync of legacy scripts.

**Comment by muhamadazmy** [comment]
It's done
now we sync 2 folders by default (legacy and jumpscripts)
The ays packages configures everything for fully automated setup. After that you have to place the scripts under the right place under the agentcontroller2 to get propagated to all agents (simply install the `legacy_js_core` package for core jumpscale legacy scripts)

https://github.com/Jumpscale/agent2/wiki/Script-distribution

**Comment by despiegk** [comment]
please put all doc in our jumpscale main doc repo
no longer in wiki pages
please check if all your content is in the main doc repo & refer from wiki
to the main doc repo


On Wed, Aug 19, 2015 at 8:04 AM, Muhamad Azmy <notifications@github.com>
wrote:

> It's done
> now we sync 2 folders by default (legacy and jumpscripts)
> The ays packages configures everything for fully automated setup. After
> that you have to place the scripts under the right place under the
> agentcontroller2 to get propagated to all agents (simply install the
> legacy_js_core package for core jumpscale legacy scripts)
>
> https://github.com/Jumpscale/agent2/wiki/Script-distribution
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/agent2/issues/8#issuecomment-132455640>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by muhamadazmy** [comment]
@despiegk I need write access to the jumpscale book to be able to update the documentation.

**Comment by zaibon** [comment]
I gave you access

**Comment by muhamadazmy** [comment]
Done
